#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 1 hour, 20 GB limit per build
# -c for confess, i.e., exit with a code if we kill the process
"$DIR"/timeout -m 20000000 -t 3600 -c /usr/bin/time "$@" || exit $?
