#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 6 hour limit per build
# -c for confess, i.e., exit with a code if we kill the process
"$DIR"/timeout -m 30000000 -t 18000 -c /usr/bin/time "$@" || exit $?
